<?php
// GateShop — central lab registry. One row per vulnerability.
// This is the single source of truth for the instructor console, the "show vulnerable code"
// panel, and the generated MANIFEST. `file` is relative to the project root; the code viewer
// reads it live and highlights the lines between the VULN: and END markers.

function labs(): array {
    return [
      // --- Injection ---
      ['slug'=>'sqli-search','title'=>'SQL injection — product search (UNION)','group'=>'Injection',
       'session'=>'P29 · SQLi — the query model','cwe'=>'CWE-89','owasp'=>'A03',
       'url'=>'/search?q=gift','file'=>'app/src/handlers/search.php','func'=>'search_products()',
       'goal'=>'Dump the users table and read the admin password hash.',
       'exploit'=>"q = ' UNION SELECT id, username, password, 4 FROM users-- -",
       'fix'=>'Parameterised query (PDO prepare/execute).'],
      ['slug'=>'sqli-login','title'=>'SQL injection — login bypass','group'=>'Injection',
       'session'=>'P29 · SQLi — the query model','cwe'=>'CWE-89','owasp'=>'A03',
       'url'=>'/login','file'=>'app/src/handlers/auth.php','func'=>'do_login()',
       'goal'=>"Log in as admin without knowing the password.",
       'exploit'=>"username = admin'-- -   password = anything",
       'fix'=>'Parameterised query; never build SQL from input.'],
      ['slug'=>'cmdi-ping','title'=>'OS command injection — network tools','group'=>'Injection',
       'session'=>'P34 · OS command injection','cwe'=>'CWE-78','owasp'=>'A03',
       'url'=>'/admin/tools','file'=>'app/src/handlers/admin.php','func'=>'net_ping()',
       'goal'=>'Run `id` / read /etc/passwd via the ping box.',
       'exploit'=>"host = 127.0.0.1; id",
       'fix'=>'escapeshellarg() + allow-list; avoid the shell entirely.'],
      ['slug'=>'xxe-import','title'=>'XXE — product XML import','group'=>'Injection',
       'session'=>'P35 · XXE','cwe'=>'CWE-611','owasp'=>'A05',
       'url'=>'/admin/import','file'=>'app/src/handlers/admin.php','func'=>'import_xml()',
       'goal'=>'Read /etc/passwd via an external entity.',
       'exploit'=>'<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]> ... &e;',
       'fix'=>'libxml_disable_entity_loader / LIBXML_NONET; disable DOCTYPE.'],
      ['slug'=>'ssti-template','title'=>'SSTI — custom message template','group'=>'Injection',
       'session'=>'P36 · SSTI','cwe'=>'CWE-1336','owasp'=>'A03',
       'url'=>'/account/signature','file'=>'app/src/handlers/account.php','func'=>'render_signature()',
       'goal'=>'Evaluate {{ 7*7 }} then run PHP via the template.',
       'exploit'=>"signature = {{ system('id') }}",
       'fix'=>'Render data, never eval templates built from user input.'],
      ['slug'=>'deserial-remember','title'=>'Insecure deserialization — remember-me cookie','group'=>'Injection',
       'session'=>'P37 · Insecure deserialization','cwe'=>'CWE-502','owasp'=>'A08',
       'url'=>'/login','file'=>'app/src/handlers/auth.php','func'=>'load_remember_cookie()',
       'goal'=>'Forge the serialized cookie to trigger a gadget / become another user.',
       'exploit'=>'Tamper the base64 PHP-serialized "remember" cookie.',
       'fix'=>'Signed tokens (HMAC) or server-side sessions; never unserialize() input.'],

      // --- Authorization / Identity ---
      ['slug'=>'idor-order','title'=>'IDOR — view any order','group'=>'Authorization',
       'session'=>'P24 · Access control & IDOR','cwe'=>'CWE-639','owasp'=>'A01',
       'url'=>'/order?id=1','file'=>'app/src/handlers/orders.php','func'=>'view_order()',
       'goal'=>"Read another customer's order by changing the id.",
       'exploit'=>'/order?id=1, 2, 3 ...',
       'fix'=>'Check the order belongs to the logged-in user.'],
      ['slug'=>'massassign-profile','title'=>'Mass assignment — become admin','group'=>'Authorization',
       'session'=>'P25 · API & mass assignment','cwe'=>'CWE-915','owasp'=>'A08',
       'url'=>'/account','file'=>'app/src/handlers/account.php','func'=>'update_profile()',
       'goal'=>'Add role=admin to the profile update and gain admin.',
       'exploit'=>'POST /account with an extra field: role=admin',
       'fix'=>'Allow-list updatable fields; never bind the whole request.'],
      ['slug'=>'bizlogic-coupon','title'=>'Business logic — coupon reuse / price tamper','group'=>'Authorization',
       'session'=>'P27 · Business logic','cwe'=>'CWE-840','owasp'=>'A04',
       'url'=>'/cart','file'=>'app/src/handlers/cart.php','func'=>'apply_coupon()',
       'goal'=>'Stack the same coupon repeatedly / set a negative quantity.',
       'exploit'=>'Apply SAVE10 many times, or qty = -5.',
       'fix'=>'Enforce one-use coupons and non-negative quantities server-side.'],
      ['slug'=>'auth-enum','title'=>'Authentication — username enumeration','group'=>'Identity',
       'session'=>'P21 · Authentication','cwe'=>'CWE-204','owasp'=>'A07',
       'url'=>'/login','file'=>'app/src/handlers/auth.php','func'=>'do_login()',
       'goal'=>'Tell valid from invalid usernames by the different error.',
       'exploit'=>'Compare "no such user" vs "wrong password".',
       'fix'=>'One generic error for both cases; constant-time-ish behaviour.'],

      // --- Capability ---
      ['slug'=>'pathtrav-invoice','title'=>'Path traversal — invoice download','group'=>'Capability',
       'session'=>'P38 · Path traversal','cwe'=>'CWE-22','owasp'=>'A01',
       'url'=>'/download?file=invoice-1.txt','file'=>'app/src/handlers/orders.php','func'=>'download_file()',
       'goal'=>'Read /etc/passwd via ../ traversal.',
       'exploit'=>'/download?file=../../../../etc/passwd',
       'fix'=>'basename() + realpath() confined to the invoices dir.'],
      ['slug'=>'upload-avatar','title'=>'File upload — avatar webshell','group'=>'Capability',
       'session'=>'P39 · File upload','cwe'=>'CWE-434','owasp'=>'A04',
       'url'=>'/account','file'=>'app/src/handlers/account.php','func'=>'upload_avatar()',
       'goal'=>'Upload a .php file and execute it from /uploads.',
       'exploit'=>'Upload shell.php containing <?php echo shell_exec($_GET["c"]);',
       'fix'=>'Allow-list extensions/MIME, store outside web root, randomise name.'],
      ['slug'=>'ssrf-fetch','title'=>'SSRF — import image from URL','group'=>'Capability',
       'session'=>'P40 · SSRF','cwe'=>'CWE-918','owasp'=>'A10',
       'url'=>'/account/avatar-url','file'=>'app/src/handlers/account.php','func'=>'fetch_avatar_url()',
       'goal'=>'Reach the internal-only endpoint and read its secret.',
       'exploit'=>'url = http://127.0.0.1/internal/flag',
       'fix'=>'Allow-list hosts/schemes; block private ranges & redirects.'],
      ['slug'=>'infodisc-debug','title'=>'Information disclosure — debug & backups','group'=>'Capability',
       'session'=>'P42 · Information disclosure','cwe'=>'CWE-200','owasp'=>'A05',
       'url'=>'/debug','file'=>'app/src/handlers/misc.php','func'=>'debug_page()',
       'goal'=>'Find the DB creds / secret leaked by debug output and backup files.',
       'exploit'=>'Visit /debug and /config.php.bak',
       'fix'=>'No debug in prod; remove backups; generic error pages.'],

      // --- Client-side ---
      ['slug'=>'xss-reflected','title'=>'XSS — reflected (search)','group'=>'Client-side',
       'session'=>'P46 · XSS','cwe'=>'CWE-79','owasp'=>'A03',
       'url'=>'/search?q=hello','file'=>'app/src/handlers/search.php','func'=>'search_products()',
       'goal'=>'Pop alert(document.domain) via the search term.',
       'exploit'=>"q = <script>alert(document.domain)</script>",
       'fix'=>'HTML-encode on output (e()).'],
      ['slug'=>'xss-stored','title'=>'XSS — stored (product reviews)','group'=>'Client-side',
       'session'=>'P46 · XSS','cwe'=>'CWE-79','owasp'=>'A03',
       'url'=>'/product?id=1','file'=>'app/src/handlers/product.php','func'=>'post_review()',
       'goal'=>'Store a review that runs JS for every visitor.',
       'exploit'=>"review = <img src=x onerror=alert(document.domain)>",
       'fix'=>'Encode on output; a strong CSP as defence in depth.'],
      ['slug'=>'xss-dom','title'=>'XSS — DOM-based (location.hash)','group'=>'Client-side',
       'session'=>'P47 · DOM-based vulns','cwe'=>'CWE-79','owasp'=>'A03',
       'url'=>'/welcome#name=hi','file'=>'app/public/assets/app.js','func'=>'renderWelcome()',
       'goal'=>'Run JS from the URL fragment (never sent to the server).',
       'exploit'=>"/welcome#name=<img src=x onerror=alert(1)>",
       'fix'=>'Use textContent, not innerHTML, for untrusted data.'],
      ['slug'=>'csrf-email','title'=>'CSRF — change email with no token','group'=>'Client-side',
       'session'=>'P48 · CSRF','cwe'=>'CWE-352','owasp'=>'A01',
       'url'=>'/account','file'=>'app/src/handlers/account.php','func'=>'update_profile()',
       'goal'=>"Change the victim's email from an attacker page.",
       'exploit'=>'Auto-submitting cross-site form POSTing /account.',
       'fix'=>'Per-session CSRF token + SameSite cookies.'],
      ['slug'=>'cors-api','title'=>'CORS — origin reflection with credentials','group'=>'Client-side',
       'session'=>'P49 · CORS & SOP','cwe'=>'CWE-942','owasp'=>'A05',
       'url'=>'/api/me','file'=>'app/src/handlers/api.php','func'=>'api_me()',
       'goal'=>"Read the victim's /api/me from evil.com.",
       'exploit'=>'fetch("/api/me",{credentials:"include"}) with a reflected Origin.',
       'fix'=>'Allow-list origins; never reflect Origin with credentials:true.'],
      ['slug'=>'clickjacking','title'=>'Clickjacking — unframed sensitive action','group'=>'Client-side',
       'session'=>'P50 · Clickjacking','cwe'=>'CWE-1021','owasp'=>'A05',
       'url'=>'/account/delete','file'=>'app/src/handlers/account.php','func'=>'delete_page()',
       'goal'=>'Frame the delete page under a decoy and steal the click.',
       'exploit'=>'Embed /account/delete in a near-transparent iframe.',
       'fix'=>"CSP frame-ancestors 'none' + X-Frame-Options: DENY."],

      // --- Advanced ---
      ['slug'=>'hosthdr-reset','title'=>'Host header — poisoned password-reset link','group'=>'Advanced',
       'session'=>'P55 · Host header attacks','cwe'=>'CWE-644','owasp'=>'A05',
       'url'=>'/forgot','file'=>'app/src/handlers/auth.php','func'=>'forgot_password()',
       'goal'=>'Make the reset link point at an attacker host.',
       'exploit'=>'Send Host: evil.com on the reset request.',
       'fix'=>'Build URLs from a fixed configured base, not the Host header.'],
      ['slug'=>'openredirect-next','title'=>'Open redirect — next parameter','group'=>'Advanced',
       'session'=>'P42 · Information disclosure','cwe'=>'CWE-601','owasp'=>'A01',
       'url'=>'/login?next=/account','file'=>'app/src/handlers/auth.php','func'=>'safe_next()',
       'goal'=>'Redirect to an external site after login.',
       'exploit'=>'/login?next=https://evil.com',
       'fix'=>'Only allow local paths starting with a single "/".'],
      ['slug'=>'webllm-gatebot','title'=>'Web LLM — prompt injection (GateBot)','group'=>'Advanced',
       'session'=>'P53 · Web LLM attacks','cwe'=>'CWE-1427','owasp'=>'A03',
       'url'=>'/support','file'=>'app/src/handlers/support.php','func'=>'gatebot_reply()',
       'goal'=>'Make the mock assistant reveal its secret / run a privileged "tool".',
       'exploit'=>'Ask it to ignore instructions; or plant the instruction in a review (indirect).',
       'fix'=>'Treat model output as untrusted; authorise tools at the API, not in the prompt.'],

      // --- Recon / Enumeration ---
      ['slug'=>'recon-discovery','title'=>'Content discovery — hidden pages & files','group'=>'Recon',
       'session'=>'P20 · Content discovery','cwe'=>'CWE-200','owasp'=>'A05',
       'url'=>'/robots.txt','file'=>'app/src/handlers/recon.php','func'=>'admin_portal() / dev_page()',
       'goal'=>'Enumerate the site and find the admin portal, staging, phpinfo and the backup leftover.',
       'exploit'=>'Read /robots.txt and /sitemap.xml; dirb/gobuster for /dev /old /phpinfo /backup.zip /admin-portal',
       'fix'=>'Remove dev/backup files; do not expose phpinfo; keep admin paths off robots and behind auth.'],
      ['slug'=>'enum-user-profile','title'=>'User enumeration — public profiles','group'=>'Recon',
       'session'=>'P21 · Authentication','cwe'=>'CWE-204','owasp'=>'A07',
       'url'=>'/users','file'=>'app/src/handlers/recon.php','func'=>'user_profile()',
       'goal'=>'Harvest every valid username by walking /user?id=1..N.',
       'exploit'=>'/user?id=1, 2, 3 … (or the /users directory)',
       'fix'=>'Require auth for profiles; use opaque identifiers; generic 404s.'],
    ];
}

function lab_by_slug(string $slug): ?array {
    foreach (labs() as $l) if ($l['slug'] === $slug) return $l;
    return null;
}
